services:

  ai-factory:

    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: ai-factory

    volumes:
      - ./:/workspace
      - ai_factory_home:/home/factory
      - claude:/home/factory/.claude

    env_file:
      - .env

    tty: true


volumes:
  ai_factory_home:
  claude: